# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Tue Nov 15 09:28:06 2022)---
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/temp.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')

## ---(Tue Nov 15 09:40:59 2022)---
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/temp.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')

## ---(Tue Nov 15 11:49:52 2022)---
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/temp.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')

## ---(Mon Nov 21 18:03:01 2022)---
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/temp.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')

## ---(Mon Dec 26 09:08:43 2022)---
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/temp.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/untitled0.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/show.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/start.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/add.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/show.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/transform.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/show.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')
runfile('C:/Users/vladi_4wnsuw3/.spyder-py3/count.py', wdir='C:/Users/vladi_4wnsuw3/.spyder-py3')